In [1]:
import pandas as pd
import numpy as np

## Reindexing

 An important method on pandas objects is reindex, which means to create a new
 object with the values rearranged to align with the new index.

In [3]:
obj = pd.Series([1, 2, 3, 4], index = ['d', 'b', 'a', 'c'])

In [4]:
obj

d    1
b    2
a    3
c    4
dtype: int64

In [5]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a    3.0
b    2.0
c    4.0
d    1.0
e    NaN
dtype: float64

In [8]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [13]:
obj3.reindex(np.arange(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [14]:
obj3.reindex(np.arange(6), method = 'ffill') # which forward-fills the values:

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [17]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'b', 'c'],
                    columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [18]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [19]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'], method = 'ffill')
frame2

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8
d     6      7           8

 The columns can be reindexed with the columns keyword:

In [20]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

Another way to reindex a particular axis is to pass the new axis labels as a positional
 argument and then specify the axis to reindex with the axis keyword:

In [23]:
frame.reindex(states, axis = 'columns')

   Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

![reindexing](Assets/reindex_methods.png)

 We can also reindex by using the loc operator

In [24]:
frame

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [28]:
frame.loc[['a', 'b', 'c'], ['California', 'Ohio']]

   California  Ohio
a           2     0
b           5     3
c           8     6

## Dropping Entries from an Axis

In [29]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [30]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [36]:
obj['c'] = 3

In [37]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
c    3.0
dtype: float64

In [39]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [40]:
obj.drop(['d', 'e'])

a    0.0
b    1.0
c    3.0
dtype: float64

With DataFrame, index values can be deleted from either axis. To illustrate this, we
 first create an example DataFrame:

In [41]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),                    
                    index=["Ohio", "Colorado", "Utah", "New York"],
                     columns=["one", "two", "three", "four"])

In [42]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data.drop(index = ['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

To drop labels from the columns, instead use the columns keyword

In [45]:
data.drop(columns=['two'])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [46]:
data.drop('two', axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [47]:
data.drop('Utah', axis=0)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [48]:
data.drop(['two', 'three'], axis = 'columns')

          one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

## Indexing, Selection, and Filtering

In [49]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [50]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [51]:
obj['a']

0.0

In [52]:
obj[2:]

c    2.0
d    3.0
dtype: float64

In [53]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [54]:
obj[['b', 'c']]

b    1.0
c    2.0
dtype: float64

In [56]:
obj[[1, 3]]

C:\Users\ahamm\AppData\Local\Temp\ipykernel_14864\2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [57]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [58]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

 the preferred way to select index values is
 with the special loc operator:

In [60]:
obj.loc[['d', 'a']]

d    3.0
a    0.0
dtype: float64

In [62]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
print(obj1)
print(obj2)

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64

In [64]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [65]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [66]:
obj2.loc['b':]

b    2
c    3
dtype: int64

In [67]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),                   
index=["Ohio", "Colorado", "Utah", "New York"],
 columns=["one", "two", "three", "four"])

In [68]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [70]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [73]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

Another use case is indexing with a Boolean DataFrame, such as one produced by
 a scalar comparison.

In [72]:
data[data['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data[data<5] = 0

In [75]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Selection on DataFrame with loc and iloc

In [76]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [87]:
data.loc[['Ohio','Utah'], ['two', 'four']]

      two  four
Ohio    0     0
Utah    9    11

In [88]:
data.loc['Utah', ['one', 'three']]

one       8
three    10
Name: Utah, dtype: int32

In [92]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data.iloc[1:, :2]

          one  two
Colorado    0    5
Utah        8    9
New York   12   13

In [95]:
data.iloc[[1, 3], [1, 2]]

          two  three
Colorado    5      6
New York   13     14

Both indexing functions work with slices in addition to single labels or lists of labels

In [99]:
data.loc[:'Utah', 'three']

Ohio         0
Colorado     6
Utah        10
Name: three, dtype: int32

In [102]:
data.iloc[:, :2][data.three > 5]

          one  two
Colorado    0    5
Utah        8    9
New York   12   13

In [104]:
data.loc[data['three'] >= 2, ['one', 'three']]

          one  three
Colorado    0      6
Utah        8     10
New York   12     14

![Index](Assets/index_operations.png)