In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to pandas Data Structures

### Series
A Series is a one-dimensional array-like object containing a sequence of values (of
similar types to NumPy types) and an associated array of data labels, called its index.

In [4]:
obj = np.array([4, 7, -5, 3])
pd.Series(obj)

0    4
1    7
2   -5
3    3
dtype: int32

In [6]:
obj = pd.Series([4, 7, -5, 3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj_2 = pd.Series([4, 7, -5, 3], index = ['a', 'b', 'c', 'd'])

In [9]:
obj_2

a    4
b    7
c   -5
d    3
dtype: int64

In [10]:
obj_2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

we can use labels in the index when selecting single
values or a set of values:

In [11]:
obj_2['a']

4

In [12]:
obj_2[['a', 'b']] # Multi-Indexing

a    4
b    7
dtype: int64

In [13]:
obj_2[obj_2 > 0]

a    4
b    7
d    3
dtype: int64

In [14]:
obj_2 * 2

a     8
b    14
c   -10
d     6
dtype: int64

When you are only passing a dict, the index in the resulting Series will have the dict’s
keys in sorted order

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj_3 = pd.Series(sdata)
obj_3 # index will be keys of dictionary

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

we can override this by passing the dict keys in the order you
want them to appear in the resulting Series:

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj_4 = pd.Series(sdata, index = states)
obj_4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

The
isnull and notnull functions in pandas should be used to detect missing data:

In [20]:
obj_4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
obj_4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj_3 + obj_4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

A Series’s index can be altered in-place by assignment:

In [26]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
A DataFrame represents a rectangular table of data and contains an ordered collection
of columns, each of which can be a different value type (numeric, string,
boolean, etc.).

In [27]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

In [28]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order:

In [30]:
pd.DataFrame(data, columns=['pop', 'year', 'state'])

   pop  year   state
0  1.5  2000    Ohio
1  1.7  2001    Ohio
2  3.6  2002    Ohio
3  2.4  2001  Nevada
4  2.9  2002  Nevada
5  3.2  2003  Nevada

If you pass a column that isn’t contained in the dict, it will appear with missing values
in the result:

In [36]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
        index=['one', 'two', 'three', 'four','five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

A column in a DataFrame can be retrieved as a Series either by dict-like notation or
by attribute:

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Rows can also be retrieved by position or name with the special loc attribute (much
more on this later):

In [45]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [47]:
frame2.loc['one':'three', 'year':'state']

       year state
one    2000  Ohio
two    2001  Ohio
three  2002  Ohio

Columns can be modified by assignment. For example, the empty 'debt' column
could be assigned a scalar value or an array of values:

In [48]:
frame2['debt'] = 0

In [49]:
frame2

       year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     0
three  2002    Ohio  3.6     0
four   2001  Nevada  2.4     0
five   2002  Nevada  2.9     0
six    2003  Nevada  3.2     0

In [50]:
frame2['debt'] = np.arange(6.)

In [51]:
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Another common form of data is a nested dict of dicts:

In [53]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [54]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [55]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

As with Series, the values attribute returns the data contained in the DataFrame as a
two-dimensional ndarray:

In [56]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### Index Objects
pandas’s Index objects are responsible for holding the axis labels and other metadata
(like the axis name or names).
![index_methods](Assets/index_methods.png)

In [58]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [63]:
index = obj.index

In [64]:
index[1:]

Index(['b', 'c'], dtype='object')

In [65]:
labels = pd.Index(np.arange(3))

In [66]:
obj_0 = pd.Series([1.5, -2.5, 0], index=labels)

In [67]:
obj_0

0    1.5
1   -2.5
2    0.0
dtype: float64